project_id = "srddxdhgxnfpxvauxjsz"

[functions.create-depot-checkout]
verify_jwt = false

[functions.create-admin]
verify_jwt = false

[functions.bootstrap-admin]
verify_jwt = false

[functions.resolve-username]
verify_jwt = false
